### ISSUE TITLE
Analog Input on NI Cards

### ISSUE THREAD

**Issue by ZJ** [JQIamo/SetList#92]
Trey would like working AI data from the NI cards.  The current situation, as per a discussion we just had:
  - AI acquisition in HW works out of the box
  - Clear Hardware.vi seems to read the samples in, but somewhere in 
![screencap](https://cloud.githubusercontent.com/assets/23578/14756030/99042390-08b4-11e6-9ecb-ce43c2f186bf.png)
The output values turn into an empty array
  - Nothing is hooked up to do the actual output.  The "old way" was a shared variable hooked onto AI Data, but with multiple NI Cards this might induce data race conditions.

**Comment by ZJ** [comment]
Pragmatically generated shared variable with device name: <DeviceName>_<AI Data> or sim.

**Comment by npisenti** [comment]
We should also see if we can move the shared variable library server ip
address to some kind of config file... I believe at the moment it's hard
coded with the strontium server IP.

**Comment by ZJ** [comment]
> at the moment it's hard coded with the strontium server IP

Is that hard-coding on the publishing side or the receiving side?  I seem to recall needing to edit in the camera acquisition programs, but then again you only ever set up shared variables the one time.

**Comment by dsbarker** [comment]
It's on the publishing side. The issue is that if you have TCP/IP devices
attached to the computer, Labview will often publish the variables to one
of the device IPs instead of to the other computer. Hardcoding the target
IP fixes the problem. A config file would be nice, if someone can figure
out how to set it up.

On Fri, Apr 22, 2016 at 8:53 PM, Z. Smith <notifications@github.com> wrote:

> at the moment it's hard coded with the strontium server IP
>
> Is that hard-coding on the publishing side or the receiving side? I seem
> to recall needing to edit in the camera acquisition programs, but then
> again you only ever set up shared variables the one time.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JQIamo/SetList/issues/92#issuecomment-213639723>
>



-- 
Joint Quantum Institute
University of Maryland
4296 Stadium Drive
College Park, MD 20742
Lab: 4254 Stadium Drive, Room 2224
301-405-4090
Office: 4254 Stadium Drive, Room 2263
301-405-1438

**Comment by ZJ** [comment]
Ah, OK, that can be put into the preferences pane with the other one-time config type settings.  Will do.

**Comment by ZJ** [comment]
Whoops, wrong direction on the title.
